language: java

sudo: false
install: true
addons:
  sonarcloud:
    organization: vishli777

jdk:
  - openjdk-21

# Для Coveralls
script:
  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Для SonarCube
#script:
#  - mvn clean install sonar:sonar -Dsonar.projectKey=VishLi777_YIVPRPO

notifications:
  email:
    recipients:
      - lidaoslavskaya@gmail.com
    on_success: always
    on_failure: always